version: 0.2

env:
  variables:
    ECR_REPO: brain-tasks-app

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo "Building Docker image with tag $IMAGE_TAG"
      - docker build -t $ECR_URI:$IMAGE_TAG -t $ECR_URI:latest .

  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push $ECR_URI:$IMAGE_TAG
      - docker push $ECR_URI:latest
      - echo "Build completed — image pushed as $ECR_URI:$IMAGE_TAG"

artifacts:
  files:
    - k8s/deployment.yaml
    - k8s/service.yaml
